### ISSUE TITLE
Rules remain if deleted before setting state to absent

### ISSUE THREAD

**Issue by sangdrax8** [Nordeus/ansible_iptables_raw#13]
I am not sure if this is something I am using incorrectly, or just not supported.  I was expecting that if I added a new custom rule on a host, and then later deleted or re-named the rule, it would be removed from the host on the next run due to the state being saved.  What I am seeing appears to leave rules in place.  If a line of a rule is removed, it does what I was expecting.

As an example.  In my host_vars I defined:
```
iptables_custom_rules:  
  - name: custom_1
    rules: | 
      -A PREROUTING -d 1.2.3.4/32 -i eth0 -j DNAT --to-destination 10.0.0.1
      -A PREROUTING -d 1.2.3.5/32 -i eth0 -j DNAT --to-destination 10.0.0.2
      -A POSTROUTING -d 1.2.3.6/32 -i eth0 -j DNAT --to-destination 10.0.0.3
    state: present
    weight: 40
    ipversion: 4
    table: nat
```

If i remove any one of those lines, they will be removed from my box.  If however I change the name from custom_1 to custom_2, I will end up with duplicate rules.  custom_1 never goes away even though it is no longer defined anywhere for my host.  I could also delete this definition, and the rules will remain on the box.  I thought anything added by ansible would be managed and therefore deleted if no longer present (or re-named).

**Comment by sangdrax8** [comment]
I have gotten around this by defining a custom rule per table, and defining only the rules inside the host variables.  Therefore the name of the rule is always the same, and if the rules are empty I can remove it all together. 

So for example in my tasks I now have:
```
- name: Set custom iptables filter
  iptables_raw:
    name: iptables_custom_filter
    weight: 40
    keep_unmanaged: '{{ iptables_keep_unmanaged }}'
    state: '{{ (iptables_custom_filter != "" ) | ternary("present", "absent") }}'
    rules: '{{ iptables_custom_filter }}'
    table: filter
  tags: iptables

- name: Set custom iptables nat
  iptables_raw:
    name: iptables_custom_nat
    weight: 40
    keep_unmanaged: '{{ iptables_keep_unmanaged }}'
    state: '{{ (iptables_custom_nat != "" ) | ternary("present", "absent") }}'
    rules: '{{ iptables_custom_nat }}'
    table: nat
  tags: iptables
```
and an individual host can define rules by overriding the default empty set which matches the table the rules should be placed in.  Using this, if a rule is deleted it will be removed from the host.

This however doesn't help much for having other modules add their own firewall rules.  If I have nginx add port 80/443, then later remove that host from having the nginx role, the firewall ports will remain even though they are no longer defined for the host.

If there is a way to have rules removed which are no longer defined for a host, that would be great because I really like this module other than this one issue I am having.
