### ISSUE TITLE
Print a message to the user if they use the `-t` parameter in rules

### ISSUE THREAD

**Issue by lioramilbaum** [Nordeus/ansible_iptables_raw#6]
playbook -
```yaml
- file: path=/etc/iptables owner=root group=root state=directory

- file: path=/etc/iptables/rules.v4 owner=root group=root state=touch

- iptables_raw:
    name: "allow_tcp_{{ item }}"
    rules: '-A INPUT -p tcp -m tcp --dport {{ item }} -j ACCEPT'
    state: present
  with_items:
    - 80
    - "{{ jenkins_http_port }}"
  
- iptables_raw:
    name: forward_port_80
    rules: "-A PREROUTING -t nat -i eth0 -p tcp --dport 80 -j REDIRECT --to-port {{ jenkins_http_port }}"
    state: present
```
output -
```
fatal: [ec2-52-208-50-86.eu-west-1.compute.amazonaws.com]: FAILED! => {"changed": false, "failed": true, "msg": "There is a problem with the iptables rules:\n\nError message:\niptables-restore v1.4.12: Line 4 seems to have a -t table option.\n\nError occurred at line: 4\nTry `iptables-restore -h' or 'iptables-restore --help' for more information.\n\nGenerated rules:\n#######\n*filter\n-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT -m comment --comment ansible[allow_tcp_80]\n-A INPUT -p tcp -m tcp --dport 8080 -j ACCEPT -m comment --comment ansible[allow_tcp_8080]\n-A PREROUTING -t nat -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8080 -m comment --comment ansible[forward_port_80]\nCOMMIT\n#####"}
```

**Comment by kustodian** [comment]
Thanks for submitting this bug report, but this isn't actually a bug. You can't use `-t nat` in the iptables rules, you have to specify a parameter `table: nat`. Your rule should be written like this:
```yaml
- iptables_raw:
    name: forward_port_80
    table: nat
    rules: "-A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port {{ jenkins_http_port }}"
    state: present
```

I guess it would be a good idea to write some kind of a message to the user if they use the `-t` parameter in the rules, so I will make sure that we add that when we release a new version.
